# Generated by roxytest: do not edit by hand!

# File R/create_new_features.R: @tests

test_that("Function create_new_features() @ L27", {
  df = read.csv("../../data/atlas-higgs-challenge-2014-v2.csv")
  df_extra = suppressWarnings(create_new_features(df))
  
  expect_equal(ncol(df_extra), 105)
  expect_false(any(is.na(df)))
})

