# Generated by roxytest: do not edit by hand!

# File R/add_pu_labels.R: @tests

test_that("Function add_pu_labels() @ L28", {
  allBackground = data.frame(Label = rep("b", 100))
  allOnes = rep(1, 100)
  expect_equal(add_pu_labels(allBackground, 1)$pu1, allOnes)
  
  allSignal= data.frame(Label = rep("b", 100))
  allZeroes = rep(0, 100)
  expect_equal(add_pu_labels(allSignal, 1)$pu1, allOnes)
  expect_equal(add_pu_labels(allBackground, 0)$pu0, allZeroes)
  
  expect_equal(sum(add_pu_labels(allBackground, 0.5)$pu0.5), 50)
})

