# Generated by roxytest: do not edit by hand!

# File R/calculate_ams.R: @tests

test_that("Function calculate_ams() @ L27", {
  y = rep(0, 5)
  w = rep(1, 5)
  expect_equal(calculate_ams(y, y, w), 30.90362, tolerance=1e-3)
  
  yhat = rep(1, 5)
  expect_equal(calculate_ams_unormalized(y, yhat, w), 0)
})


test_that("Function calculate_ams_unormalized() @ L63", {
  y = rep(0, 5)
  w = rep(1, 5)
  expect_equal(calculate_ams_unormalized(y, y, w), 0)
  
  yhat = rep(1, 5)
  expect_equal(calculate_ams_unormalized(y, yhat, w), 0)
})

